# This is a basic workflow to help you get started with Actions
name: Test & deployement

on:
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
         java-version: '17'
         distribution: 'adopt'

    - name: Construire le projet
      run: mvn clean install 

    - name: Executer les tests
      run: mvn test  # Exécute les tests unitaires

    - name: Checkout Repository
      uses: 'actions/checkout@v2'
      with:
        ref: main
        token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

    - name: Create GitHub deployment
      uses: chrnorm/deployment-action@v2
      id: deployment
      with:
          token: '${{ secrets.PERSONAL_GITHUB_TOKEN }}'
          environment-url: ${{ vars.MY_APP }}
          environment: production  
    

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
  # This workflow contains a single job called "build"
  # build:
    # The type of runner that the job will run on
    # runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    # steps:
    #  - name: Checkout Repository
    #    uses: 'actions/checkout@v2'
    #    with:
    #     ref: main
    #     token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

    #  - name: Create GitHub deployment
    #    uses: chrnorm/deployment-action@v2
    #    id: deployment
    #    with:
    #       token: '${{ github.token }}'
    #       environment-url: ${{ vars.MY_APP }}
    #       environment: production

    #  - name: Deploy using ssh
    #    env:
    #       GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
    #    with:
    #       host: ${{ secrets.VPS_IP }}
    #       username: ${{ secrets.VPS_USERNAME }}
    #       key: ${{ secrets.SSH_PRIVATE_KEY }}
    #       passphrase: ${{ secrets.SSH_PASSPHRASE }}
    #       port: 22
    #       script: |
    #         mvn compile